[package]
name = "gci"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79" }
dialoguer = { version = "0.11.0" }
git2 = { version = "0.18.2", default-features = false }
